#!/bin/bash
# Quick deployment to Railway

echo "🚀 Deploying AI Agents to Railway"
echo "================================="
echo ""
echo "Since Railway CLI needs interactive login, please run these commands manually:"
echo ""
echo "1. First, add Railway to your PATH:"
echo "   export PATH=\"\$PATH:/Users/jaimeortiz/.npm-global/bin\""
echo ""
echo "2. Login to Railway:"
echo "   railway login"
echo ""
echo "3. Link to your existing project:"
echo "   railway link"
echo ""
echo "4. Deploy the code:"
echo "   railway up"
echo ""
echo "5. Check the deployment:"
echo "   railway status"
echo ""
echo "6. View logs:"
echo "   railway logs -f"
echo ""
echo "================================="
echo ""
echo "Or copy and run this one-liner after logging in:"
echo ""
echo "cd /Users/jaimeortiz/Test\ Main/metaads-new && railway link && railway up && railway status"
echo ""
echo "Your Flask app with AI agents will be deployed!"