[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 3000

[env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"